applicationId: "1206315369430519819"

username: "" # Your RailMiles username
url: ""      # Your RailMiles public site URL

mode: "solo" # Can be solo or league
league: 0    # If mode is league, this is the league ID

messages:
  topSoloMessage: "{mi} miles and {ch} chains"
  bottomSoloMessage: "{place} place - {mi}mi and {ch}ch in {year}"
  topLeagueMessage: "{place} place - {mi}mi and {ch}ch in {year}"
  bottomLeagueMessage: "Competing in {leagueName}"

buttons:
  userLink:
    visible: true
    message: "My RailMiles"
  leagueLink: 
    visible: true # Setting will only work in league mode
    message: "View League"


imageKeys:   # Custom application image keys 
  largeImage: "dsc_027-e"
  smallImage: ""